ALTER TABLE public.monitored_profiles
  ADD COLUMN IF NOT EXISTS follows_count INTEGER,
  ADD COLUMN IF NOT EXISTS profile_views_30d INTEGER,
  ADD COLUMN IF NOT EXISTS website_clicks_30d INTEGER,
  ADD COLUMN IF NOT EXISTS reach_30d INTEGER,
  ADD COLUMN IF NOT EXISTS impressions_30d INTEGER,
  ADD COLUMN IF NOT EXISTS audience_gender_age JSONB,
  ADD COLUMN IF NOT EXISTS audience_city JSONB,
  ADD COLUMN IF NOT EXISTS audience_country JSONB,
  ADD COLUMN IF NOT EXISTS posts_data JSONB,
  ADD COLUMN IF NOT EXISTS total_posts_30d INTEGER;